name: wtf
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14648
title: '|W|T|F|'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff200'
    - '#231f20'
    - '#6d6e71'
    - '#a7a9ac'
    - '#f4e815'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
