name: wtf
favicon: null
layout_spectrum: 0.817096438491717
typography_spectrum: 0.9914869358763099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6441055769100785
  lightness: 0.9889087497722358
  saturation: 0.4746512952260673
  rhythmicContrast: 0.3704896492417902
purpose: []
